enum langEnum {
  English,
  Bangla,
//  Chinese,
  Spanish,
  Arabic,
  French
}

List<String> langList = [
  "English",
  "বাংলা",
//  "中文",
  "Español",
  "عربى",
  "Français"
];

Map<String, String> English = {
  "Forgot password ?" : "Forgot password ?",
  "Recover password" : "Recover password",
  "Title": "Title",
  "Leave a review": "Leave a review",
  "Review content": "Review content",
  "Service": "Service",
  "Organization": "Organization",
  "Friendliness": "Friendliness",
  "Area Expert": "Area Expert",
  "Safety": "Safety",
  "No reviews to display": "No reviews to display",

  "Menu": "Menu",
  "Edit Profile": "Edit Profile",
  "Notification": "Notification",
  "Home": "Home",
  "Favourite": "Favourite",
  "Profile": "Profile",
  "Search": "Search",
  "History": "History",
  "Report": "Report",
  "Currency": "Currency",
  "Settings": "Settings",
  "Language": "Language",
  "Visa": "Visa",
  "Log out": "Log out",
  "Password": "Password",
  "Could not log out": "Could not log out",
  "ALL BOOKING": "ALL BOOKING",
  "COMPLETED": "COMPLETED",
  "PROCESSING": "PROCESSING",
  "CONFIRMED": "CONFIRMED",
  "CANCELLED": "CANCELLED",
  "PAID": "PAID",
  "UNPAID": "UNPAID",
  "Booking History": "Booking History",
  "View info": "View info",
  "Type": "Type",
  "Cost": "Cost",
  "Order date": "Order date",
  "Start date": "Start date",
  "End date": "End date",
  "Status": "Status",
  "Booking Status": "Booking Status",
  "Booking Date": "Booking Date",
  "Payment Method": "Payment Method",
  "Duration": "Duration",
  "Guests": "Guests",
  "Service fee": "Service fee",
  "Discount": "Discount",
  "Booking detail": "Booking detail",
  "Booking Detail": "Booking Detail",
  "User detail": "User detail",
  "First name": "First name",
  "Last name": "Last name",
  "Balance": "Balance",
  "Reward points": "Reward points",
  "Create request": "Add Fund",
  "Convert points to balance": "Convert",
  "My Wallet": "My Wallet",
  "Wallet History": "Wallet history",
  "Balance HIstory": "Balance HIstory",
  "Reward History": "Reward History",
  "Amount": "Amount",
  "Date": "Date",
  "Purpose": "Purpose",
  "Debit": "Debit",
  "Credit": "Credit",
  "Request Date": "Request Date",
  "Processing Date": "Processing Date",
  "Info": "Info",
  "Change Currency": "Change Currency",
  "Business name": "Business name",
  "First name": "First name",
  "Last name": "Last name",
  "Email": "Email",
  "Phone": "Phone",
  "Birthday": "Birthday",
  "About yourself": "About yourself",
  "Address": "Address",
  "Alternative address": "Alternative address",
  "City": "City",
  "State": "State",
  "Country": "Country",
  "Zip code": "Zip code",
  "Save": "Save",
  "must be filled": "must be filled",
  "Select nationality": "Select nationality",
  "Select destination": "Select destination",
  "Search and apply for visa online": "Search and apply for visa online",
  "Change Password": "Change Password",
  "Enter Current password": "Enter Current password",
  "Enter New password": "Enter New password",
  "Confirm New password": "Confirm New password",
  "Cancel": "Cancel",
  "Change": "Change",
  "No data to display": "No data to display",
  "Search Tour": "Search Tour",
  "Search Hotels, Tour, Room, Transport all over the world":
  "Search Hotels, Tour, Room, Transport all over the world",
  "Tours": "Tours",
  "Hotels": "Hotels",
  "Rooms": "Rooms",
  "Transport": "Transport",
  "Transports": "Transports",
  "Search Hotel": "Search Hotel",
  "Search Destination": "Search Destination",
  "Choose date": "Choose date",
  "Starting date": "Starting date",
  "Ending date": "Ending date",
  "Room": "Room",
  "Child": "Child",
  "Adult": "Adult",
  "Adults": "Adult",
  "Search Hotels": "Search Hotels",
  "Search tour": "Search Tour",
  "Search Room": "Search Room",
  "Search Rooms": "Search Rooms",
  "Search Transport": "Search Transport",
  "Search Transports": "Search Transports",
  "Where would you\nlike to go?": "Where would you\nlike to go?",
  "Offers": "Offers",
  "Apply for visa": "Apply for visa",
  "Travel tips": "Travel tips",
  "Bestseller Listing": "Bestseller Listing",
  "Top Destination": "Top Destination",
  "Top Destinations": "Top Destinations",
  "Our best promotion tours": "Our best promotion tours",
  "See All": "See All",
  "Okay": "Okay",
  "Close": "Close",
  "No record": "No record",
  "Apply now": "Apply now",
  "Visa Cost": "Visa Cost",
  "Processing Cost": "Processing Cost",
  "Processing time": "Processing time",
  "Basic Information": "Basic Information",
  "Apply for visa": "Apply for Visa",
  "Add Applicant": "Add Applicant",
  "No applicant added": "No applicant added",
  "Processing Time and Fee": "Processing Time and Fee",
  "Add": "Add",
  "Total visa cost": "Total visa cost",
  "General Information": "General Information",
  "Revision and Payment": "Revision and Payment",
  "Done and Payment": "Done and Payment",
  "Book Transports Easily": "Book Transports Easily",
  "Find  Tours Easily": "Find  Tours Easily",
  "Find rooms easily": "Find rooms easily",
  "Find hotels easily": "Find hotels easily",
  "Search Tours": "Search Tours",
  "results": "results",
  "Book now": "Book now",
  "Book Now": "Book now",
  "Total price": "Total price",
  "you must choose starting and ending date":
  "you must choose starting and ending date",
  "you must choose starting date": "you must choose starting date",
  "Please choose ending date": "Please choose ending date",
  "Please choose number of people": "Please choose number of people",
  "Check availability": "Check availability",
  "Choose your date, find room , \n book and enjoy":
  "Choose your date, find room , \n book and enjoy",
  "Book Hotel": "Book Hotel",
  "Choose date, person number and book hotel":
  "Choose date, person number and book hotel",
  "Submit": "Submit",
  "Total Adults": "Total Adults",
  "Total Children": "Total Children",
  "Total guest": "Total guest",
  "Booked Rooms": "Booked Rooms",
  "Total": "Total",
  "Pay using": "Pay using",
  "Your total wallet balance": "Your total wallet balance",
  "Redeem full wallet balance": "Redeem full wallet balance",
  "Use maximum wallet balance for the payment":
  "Use maximum wallet balance for the payment",
  "Redeem Specific Amount": "Redeem Specific Amount",
  "Enter amount you wish to pay from wallet":
  "Enter amount you wish to pay from wallet",
  "Booking Submission": "Booking Submission",
  "Book Room": "Book Room",
  "Book Tour": "Book Tour",
  "Not Set": "Not Set",
  "Not set": "Not Set",
  "Book Transport": "Book Transport",
  "Number": "Number",
  "Extra Prices": "Extra Prices",
  "DETAIL": "DETAIL",
  "Agent Comission": "Agent Comission",
  "Agent comission": "Agent Comission",
  "Apply Instruction": "Apply Instruction",
  "No data to display": "No data to display",
  "You are not logged in, \n please login to access all features":
  "You are not logged in, \n please login to access all features",
  "Create account": "Create account",
  "Log In": "Log In",
  "Login": "Login",
  "Don\'t have account? Sign up": "Don\'t have account? Sign up",
  "Have account? Log in": "Have account? Log in",
  "Please Enter Email": "Please Enter Email",
  "Please Enter Password": "Please Enter Password",
  "Confirm Password": "Confirm Password",
  "Sign up": "Sign up",
  "I have read and accept the Terms and Privacy Policy":
  "I have read and accept the Terms and Privacy Policy",
  "Overview": "Overview",
  "You might also like": "You might also like",
  "you might also like": "You might also like",
  "Reviews": "Reviews",
  "Included": "Included",
  "Excluded": "Excluded",
};

Map<String, String> Bangla = {
  "Forgot password ?" : "পাসওয়ার্ড ভুলে গেছেন ?",
  "Recover password" : "পরিবর্তনকারী চাবিকাঠি",
  "Title": "শিরোনাম",
  "Leave a review": "একটি পর্যালোচনা ছেড়ে দিন",
  "Review content": "বিষয়বস্তু পর্যালোচনা",
  "Service": "সেবা",
  "Organization": "সংগঠন",
  "Friendliness": "বন্ধুভাবাপন্নতা",
  "Area Expert": "অঞ্চল বিশেষজ্ঞ",
  "Safety": "নিরাপত্তা",
  "No reviews to display": "প্রদর্শনের জন্য কোনও পর্যালোচনা নেই",

  "Menu": "তালিকা",
  "Edit Profile": "প্রোফাইল সম্পাদনা",
  "Notification": 'নোটিফিকেশন',
  "Excluded": "অপসারণ",
  "Included": "অন্তর্ভুক্ত",
  "Reviews": "পর্যালোচনা",
  "You might also like": "তুমি এটাও পছন্দ করতে পারো",
  "you might also like": "তুমি এটাও পছন্দ করতে পারো",
  "Please Enter Email": "ইমেল প্রবেশ করুন",
  "Please Enter Password": "পাসওয়ার্ড লিখুন দয়া করে",
  "Book Room": "রুম বুকিং",
  "Booking Submission": "বুকিং জমা",
  "Enter amount you wish to pay from wallet":
  "মানিব্যাগ থেকে আপনি যে পরিমাণ অর্থ প্রদান করতে চান তা প্রবেশ করুন",
  "Redeem Specific Amount": "নির্দিষ্ট পরিমাণ পরিশোধ করুন",
  "Use maximum wallet balance for the payment":
  "অর্থ প্রদানের জন্য সর্বাধিক ওয়ালেট ব্যালেন্স ব্যবহার করুন",
  "Redeem full wallet balance": "পূর্ণ ওয়ালেটের ভারসাম্য মুক্ত করুন",
  "Book Tour": "ট্যুর বুকিং",
  "Not Set": "সেট না",
  "Not set": "সেট না",
  "Book Transport": "পরিবহন বুকিং",
  "Number": "সংখ্যা",
  "Extra Prices": "অতিরিক্ত দাম",
  "DETAIL": "বিস্তারিত",
  "Agent Comission": "এজেন্ট কমিশন",
  "Agent comission": "এজেন্ট কমিশন",
  "Apply Instruction": "নির্দেশ প্রয়োগ করুন",
  "No data to display": "কোনও তথ্য নেই",
  "You are not logged in, \n please login to access all features":
  "আপনি লগইন নেই,\n সমস্ত বৈশিষ্ট্য অ্যাক্সেস করতে লগইন করুন",
  "Create account": "অ্যাকাউন্ট তৈরি করুন",
  "Log In": "প্রবেশ করুন",
  "Login": "প্রবেশ করুন",
  "Don\'t have account? Sign up": "অ্যাকাউন্ট নেই? সাইন আপ করুন",
  "Have account? Log in": "অ্যাকাউন্ট আছে? প্রবেশ করুন",
  "Confirm Password": "পাসওয়ার্ড নিশ্চিত করুন",
  "Sign up": "নিবন্ধন করুন",
  "I have read and accept the Terms and Privacy Policy":
  "আমি শর্তাদি এবং গোপনীয়তা নীতি পড়েছি এবং গ্রহণ করেছি",
  "Overview": "সংক্ষিপ্ত বিবরণ",
  "Home": "হোম পৃষ্ঠা",
  "Favourite": "প্রিয়",
  "Profile": "প্রোফাইল",
  "Search": "অনুসন্ধান",
  "History": "ইতিহাস",
  "Report": "প্রতিবেদন করুন",
  "Currency": "মুদ্রা",
  "Settings": "সেটিংস",
  "Language": "ভাষা",
  "Visa": "ভিসা",
  "Log out": "প্রস্থান",
  "Password": "পাসওয়ার্ড",
  "Could not log out": "লগ আউট করা যায়নি",
  "ALL BOOKING": "সমস্ত বুকিং",
  "COMPLETED": "সম্পন্ন",
  "PROCESSING": "প্রসেসিং",
  "CONFIRMED": "নিশ্চিত",
  "CANCELLED": "বাতিল",
  "PAID": "দেওয়া",
  "UNPAID": "অবৈতনিক",
  "Booking History": "বুকিংয়ের ইতিহাস",
  "View info": "তথ্য দেখুন",
  "Type": "নমুনা",
  "Cost": "মূল্য",
  "Order date": "অর্ডারের তারিখ",
  "Start date": "শুরুর তারিখ",
  "End date": "শেষ তারিখ",
  "Status": "স্থিতি",
  "Booking Status": "বুকিংয়ের স্থিতি",
  "Booking Date": "বুকিং তারিখ",
  "Payment Method": "মূল্যপরিশোধ পদ্ধতি",
  "Duration": "স্থিতিকাল",
  "Guests": "অতিথিরা",
  "Service fee": "পরিসেবা চার্জ",
  "Discount": "ছাড়",
  "Booking detail": "বুকিং বিশদ",
  "Booking Detail": "বুকিং বিশদ",
  "User detail": "ব্যবহারকারীর বিবরণ",
  "First name": "নামের প্রথম অংশ",
  "Last name": "নামের শেষাংশ",
  "Balance": "বর্তমান হিসাব",
  "Reward points": "বর্তমান পুরষ্কার পয়েন্ট",
  "Create request": "অনুরোধ তৈরি করুন",
  "Convert points to balance": "পয়েন্টগুলি রূপান্তর করুন",
  "My Wallet": "আমার মানিব্যাগ",
  "Wallet history": "মানিব্যাগের ইতিহাস",
  "Reward History": "পুরষ্কারের ইতিহাস",
  "Amount": "পরিমাণ",
  "Date": "তারিখ",
  "Purpose": "উদ্দেশ্য",
  "Debit": "ডেবিট",
  "Credit": "ক্রেডিট",
  "Request Date": "অনুরোধ তারিখ",
  "Processing Date": "প্রক্রিয়াজাতকরণের তারিখ",
  "Info": "তথ্য",
  "Change Currency": "মুদ্রা পরিবর্তন",
  "Business name": "প্রাতিষ্ঠানিক নাম",
  "First name": "নামের প্রথম অংশ",
  "Last name": "নামের শেষাংশ",
  "Email": "ইমেইল",
  "Phone": "ফোন",
  "Birthday": "জন্মদিন",
  "About yourself": "নিজের সম্পর্কে",
  "Address": "ঠিকানা",
  "Alternative address": "বিকল্প ঠিকানা",
  "City": "শহর",
  "State": "রাষ্ট্র",
  "Country": "দেশ",
  "Zip code": "জিপ কোড",
  "Save": "সংরক্ষণ",
  "must be filled": "অবশ্যই পূরণ করা উচিত",
  "Select nationality": "জাতীয়তা নির্বাচন করুন",
  "Select destination": "গন্তব্য নির্বাচন করুন",
  "Search and apply for visa online":
  "অনলাইনে ভিসার জন্য অনুসন্ধান এবং আবেদন করুন",
  "Change Password": "পাসওয়ার্ড পরিবর্তন করুন",
  "Enter Current password": "বর্তমান পাসওয়ার্ড লিখুন",
  "Enter New password": "নতুন পাসওয়ার্ড লিখুন",
  "Confirm New password": "নিশ্চিত কর নতুন গোপননম্বর",
  "Cancel": "বাতিল",
  "Change": "পরিবর্তন",
  "No data to display": "প্রদর্শনের জন্য কোনও ডেটা নেই",
  "Search Tour": "অনুসন্ধান ভ্রমণ",
  "Search Hotels, Tour, Room, Transport all over the world":
  "সারা বিশ্বে হোটেল, ভ্রমণ, ঘর, পরিবহন অনুসন্ধান করুন",
  "Tours": "ট্যুর",
  "Hotels": "হোটেল",
  "Rooms": "রুম",
  "Transport": "পরিবহন",
  "Transports": "পরিবহন",
  "Search Destination": "অনুসন্ধান গন্তব্যস্থান",
  "Choose date": "তারিখ নির্বাচন করুন",
  "Starting date": "শুরু তারিখ",
  "Ending date": "সমাপ্তির তারিখ",
  "Room": "রুম",
  "Child": "শিশু",
  "Adult": "পূর্ণবয়স্ক",
  "Adults": "পূর্ণবয়স্ক",
  "Search tour": "অনুসন্ধান ভ্রমণ",
  "Search Hotels": "অনুসন্ধান হোটেল",
  "Search Hotel": "অনুসন্ধান হোটেল",
  "Search Room": "অনুসন্ধান ঘর",
  "Search Rooms": "অনুসন্ধান ঘর",
  "Search Transport": "অনুসন্ধান পরিবহন",
  "Search Transports": "অনুসন্ধান পরিবহন",
  "Where would you\nlike to go?": "আপনি কোথায় যেতে চান?",
  "Offers": "অফার",
  "Apply for visa": "ভিসার জন্য আবেদন করুন",
  "Travel tips": "ভ্রমন পরামর্শ",
  "Bestseller Listing": "বেস্টসেলার তালিকা",
  "Top Destination": "শীর্ষস্থানীয় গন্তব্য",
  "Top Destinations": "শীর্ষস্থানীয় গন্তব্য",
  "Our best promotion tours": "আমাদের সেরা প্রচার ট্যুর",
  "See All": "সবগুলো দেখ",
  "Okay": "ঠিক আছে",
  "Close": "বন্ধ",
  "No record": "কোন রেকর্ড নেই",
  "Apply now": "এখন আবেদন কর",
  "Visa Cost": "ভিসা খরচ",
  "Processing Cost": "প্রসেসিং ব্যয়",
  "Processing time": "প্রক্রিয়াকরণের সময়",
  "Basic Information": "মৌলিক তথ্",
  "Apply for visa": "ভিসার জন্য আবেদন করুন",
  "Add Applicant": "আবেদনকারী যুক্ত করুন",
  "No applicant added": "কোনও আবেদনকারী যুক্ত হয়নি",
  "Processing Time and Fee": "প্রসেসিং সময় এবং ফি",
  "Add": "যোগ",
  "Total visa cost": "মোট ভিসার ব্যয়",
  "General Information": "সাধারণ জ্ঞাতব্য",
  "Revision and Payment": "সংশোধন ও প্রদান",
  "Done and Payment": "সম্পন্ন এবং অর্থ প্রদান",
  "Book Transports Easily": "সহজেই ট্রান্সপোর্টগুলি বুক করুন",
  "Find  Tours Easily": "সহজে ভ্রমণ করুন",
  "Find rooms easily": "সহজেই রুমগুলি সন্ধান করুন",
  "Find hotels easily": "হোটেলগুলি সহজেই সন্ধান করুন",
  "Search Tours": "অনুসন্ধান ট্যুর",
  "results": "ফলাফল",
  "Book now": "এখনই বুক করুন",
  "Book Now": "এখনই বুক করুন",
  "Total price": "মোট দাম",
  "you must choose starting and ending date":
  "আপনাকে অবশ্যই শুরু এবং শেষের তারিখটি বেছে নিতে হবে",
  "you must choose starting date": "আপনাকে অবশ্যই শুরুর তারিখটি বেছে নিতে হবে",
  "Please choose ending date": "আপনাকে অবশ্যই শেষের তারিখটি বেছে নিতে হবে",
  "Please choose number of people": "দয়া করে লোক সংখ্যা নির্বাচন করুন",
  "Check availability": "গ্রহণযোগ্যতা যাচাই",
  "Choose your date, find room , \n book and enjoy":
  "আপনার তারিখ চয়ন করুন, ঘর সন্ধান করুন, \n এবং উপভোগ করুন",
  "Book Hotel": "হোটেল বুকিং",
  "Choose date, person number and book hotel":
  "তারিখ, ব্যক্তির নম্বর এবং বুক হোটেল চয়ন করুন",
  "Submit": "জমা দিন",
  "Total Adults": "মোট প্রাপ্তবয়স্কদের",
  "Total Children": "মোট শিশু",
  "Total guest": "মোট অতিথি",
  "Booked Rooms": "বুকিং রুম",
  "Total": "মোট",
  "Pay using": "ব্যবহার করে অর্থ প্রদান করুন",
  "Your total wallet balance": "আপনার মোট ওয়ালেট ব্যালেন্স",
};

Map<String, String> Chinese = {
  "Home": "家",
  "Favourite": "喜爱",
  "Profile": "轮廓",
  "Search": "Search"
};

Map<String, String> Spanish = {
  "Forgot password ?" : "Se te olvidó tu contraseña ?",
  "Recover password" : "Recuperar contraseña",
  "Title": "Título",
  "Leave a review": "Dejar un comentario",
  "Review content": "Revisar contenido",
  "Service": "Servicio",
  "Organization": "Organización",
  "Friendliness": "Amabilidad",
  "Area Expert": "Experta en el área",
  "Safety": "La seguridad",
  "No reviews to display": "No hay comentarios para mostrar",

  "Menu": "Menú",
  "Edit Profile": "Editar perfil",
  "Notification": "Notificación",
  "Home": "Hogar",
  "Favourite": "Favorita",
  "Profile": "Perfil",
  "Search": "Buscar",
  "History": "Historia",
  "Report": "Reporte",
  "Currency": "Currency",
  "Settings": "Moneda",
  "Language": "Idioma",
  "Visa": "Visa",
  "Log out": "Cerrar sesión",
  "Password": "Contraseña",
  "Could not log out": "No se pudo cerrar sesión",
  "ALL BOOKING": "TODAS LAS RESERVAS",
  "COMPLETED": "TERMINADA",
  "PROCESSING": "PROCESANDO",
  "CONFIRMED": "CONFIRMADA",
  "CANCELLED": "CANCELADA",
  "PAID": "PAGADA",
  "UNPAID": "NO PAGADO",
  "Booking History": "Historial de reservas",
  "View info": "Ver información",
  "Type": "Tipo",
  "Cost": "Cost",
  "Order date": "Costo",
  "Start date": "Fecha de inicio",
  "End date": "Fecha final",
  "Status": "Estado",
  "Booking Status": "Estado de la reservación",
  "Booking Date": "Fecha para registrarse",
  "Payment Method": "Método de pago",
  "Duration": "Duración",
  "Guests": "Invitadas",
  "Service fee": "Tarifa de servicio",
  "Discount": "Descuento",
  "Booking detail": "Detalle de reserva",
  "Booking Detail": "Detalle de reserva",
  "User detail": "Detalle del usuario",
  "First name": "Nombre de pila",
  "Last name": "Apellido",
  "Balance": "Saldo actual",
  "Reward points": "Puntos de recompensa actuales",
  "Create request": "Crear solicitud",
  "Convert points to balance": "Convertir puntos en equilibrio",
  "My Wallet": "Mi billetera",
  "Wallet History": "Historial de billetera",
  "Balance HIstory": "Balance de historia",
  "Reward History": "Historia de recompensa",
  "Amount": "Cantidad",
  "Date": "Fecha",
  "Purpose": "Propósito",
  "Debit": "Débito",
  "Credit": "Crédito",
  "Request Date": "Fecha de solicitud",
  "Processing Date": "Fecha de procesamiento",
  "Info": "Informacion",
  "Change Currency": "Cambiar moneda",
  "Business name": "Nombre del Negocio",
  "First name": "Nombre de pila",
  "Last name": "Apellido",
  "Email": "Email",
  "Phone": "Teléfono",
  "Birthday": "Cumpleaños",
  "About yourself": "Acerca de ti mismo",
  "Address": "Habla a",
  "Alternative address": "Dirección alternativa",
  "City": "Ciudad",
  "State": "Estado",
  "Country": "País",
  "Zip code": "Código postal",
  "Save": "Salvar",
  "must be filled": "debe ser llenado",
  "Select nationality": "Seleccionar nacionalidad",
  "Select destination": "Seleccionar destino",
  "Search and apply for visa online": "Busque y solicite visa en línea",
  "Change Password": "Cambia la contraseña",
  "Enter Current password": "Enter Current password",
  "Enter New password": "Introducir la contraseña actual",
  "Confirm New password": "Confirmar nueva contraseña",
  "Cancel": "Cancelar",
  "Change": "Cambio",
  "No data to display": "no hay información para mostrar",
  "Search Tour": "Buscar recorrido",
  "Search Hotels, Tour, Room, Transport all over the world":
  "Buscar hoteles, recorridos, habitaciones, transporte en todo el mundo",
  "Tours": "Excursiones",
  "Hotels": "Hoteles",
  "Rooms": "Habitaciones",
  "Transport": "Transporte",
  "Transports": "Transportes",
  "Search Hotel": "Buscar hotel",
  "Search Destination": "Buscar destino",
  "Choose date": "Elige fecha",
  "Starting date": "Fecha de inicio",
  "Ending date": "Fecha de finalización",
  "Room": "Habitación",
  "Child": "Niña",
  "Adult": "Adulta",
  "Adults": "Adulta",
  "Search Hotels": "Buscar hoteles",
  "Search tour": "Buscar recorrido",
  "Search Room": "Sala de búsqueda",
  "Search Rooms": "Buscar habitaciones",
  "Search Transport": "Buscar transporte",
  "Search Transports": "Buscar transportes",
  "Where would you\nlike to go?": "¿Dónde te gustaría ir?",
  "Offers": "Ofertas",
  "Apply for visa": "Aplicar para visa",
  "Travel tips": "Consejos de viaje",
  "Bestseller Listing": "Listado de los más vendidos",
  "Top Destination": "Destino superior",
  "Top Destinations": "Mejores destinos",
  "Our best promotion tours": "Nuestros mejores tours promocionales",
  "See All": "Ver todo",
  "Okay": "Bueno",
  "Close": "Cerca",
  "No record": "Sin registro",
  "Apply now": "Aplica ya",
  "Visa Cost": "Costo de visa",
  "Processing Cost": "Costo de procesamiento",
  "Processing time": "Tiempo de procesamiento",
  "Basic Information": "Información básica",
  "Apply for visa": "Aplicar para visa",
  "Add Applicant": "Añadir solicitante",
  "No applicant added": "Ningún solicitante agregado",
  "Processing Time and Fee": "Tiempo de procesamiento y tarifa",
  "Add": "Añadir",
  "Total visa cost": "Costo total de la visa",
  "General Information": "Información general",
  "Revision and Payment": "Revisión y pago",
  "Done and Payment": "Hecho y pago",
  "Book Transports Easily": "Transportes de libros fácilmente",
  "Find  Tours Easily": "Encuentra tours fácilmente",
  "Find rooms easily": "Encuentra habitaciones fácilmente",
  "Find hotels easily": "Encuentra hoteles fácilmente",
  "Search Tours": "Buscar recorridos",
  "results": "resultados",
  "Book now": "Reservar ahora",
  "Book Now": "Reservar ahora",
  "Total price": "Precio total",
  "you must choose starting and ending date":
  "debes elegir la fecha de inicio y finalización",
  "you must choose starting date": "debes elegir la fecha de inicio",
  "Please choose ending date": "Por favor elija la fecha de finalización",
  "Please choose number of people": "Por favor, elija el número de personas",
  "Check availability": "Consultar disponibilidad",
  "Choose your date, find room , \n book and enjoy":
  "Elige tu fecha, encuentra habitación, \n reserva y disfruta",
  "Book Hotel": "Reservar hotel",
  "Choose date, person number and book hotel":
  "Elige fecha, número de persona y reserva hotel",
  "Submit": "Enviar",
  "Total Adults": "Adultos totales",
  "Total Children": "Total de niñas",
  "Total guest": "Invitada total",
  "Booked Rooms": "Cuartos reservados",
  "Total": "Total",
  "Pay using": "Paga usando",
  "Your total wallet balance": "Su saldo total de billetera",
  "Redeem full wallet balance": "Canjear el saldo completo de la billetera",
  "Use maximum wallet balance for the payment":
  "Use el saldo máximo de la billetera para el pago",
  "Redeem Specific Amount": "Canjear Monto Específico",
  "Enter amount you wish to pay from wallet":
  "Ingrese el monto que desea pagar de la billetera",
  "Booking Submission": "Envío de reserva",
  "Book Room": "Reservar habitación",
  "Book Tour": "Tour del libro",
  "Not Set": "No establecido",
  "Not set": "No establecido",
  "Book Transport": "Transporte de libros",
  "Number": "Número",
  "Extra Prices": "Precios extra",
  "DETAIL": "DETALLE",
  "Agent Comission": "Agente de comisión",
  "Agent comission": "Agente de comisión",
  "Apply Instruction": "Aplicar instrucción",
  "No data to display": "no hay información para mostrar",
  "You are not logged in, \n please login to access all features":
  "No ha iniciado sesión, \n inicie sesión para acceder a todas las funciones",
  "Create account": "Crear una cuenta",
  "Log In": "Log In",
  "Login": "Iniciar sesión",
  "Don\'t have account? Sign up": "¿No tienes cuenta? Regístrate",
  "Have account? Log in": "¿Tienes cuenta? Iniciar sesión",
  "Please Enter Email": "Por favor ingrese su correo electrónico",
  "Please Enter Password": "Por favor, ingrese contraseña",
  "Confirm Password": "Confirmar contraseña",
  "Sign up": "Regístrate",
  "I have read and accept the Terms and Privacy Policy":
  "He leído y acepto los Términos y la Política de privacidad",
  "Overview": "Visión general",
  "You might also like": "También podría gustarte",
  "you might also like": "También podría gustarte",
  "Reviews": "Comentarios",
  "Included": "Incluida",
  "Excluded": "Excluida",
};

Map<String, String> Arabic = {
  "Forgot password ?" : "هل نسيت كلمة المرور ؟",
  "Recover password" : "إستعادة كلمة المرور",
  "Title": "عنوان",
  "Leave a review": "ترك التعليق",
  "Review content": "مراجعة المحتوى",
  "Service": "الخدمات",
  "Organization": "منظمة",
  "Friendliness": "الود",
  "Area Expert": "خبير المنطقة",
  "Safety": "سلامة",
  "No reviews to display": "ليست هناك مراجعات لعرضها",

  "Menu": "قائمة طعام",
  "Edit Profile": "تعديل الملف الشخصي",
  "Notification": "تنبيه",
  "Excluded": "مستبعد",
  "Included": "مشمول",
  "Reviews": "المراجعات",
  "You might also like": "قد يعجبك ايضا",
  "you might also like": "قد يعجبك ايضا",
  "Please Enter Email": "الرجاء إدخال البريد الإلكتروني",
  "Please Enter Password": "الرجاء إدخال كلمة المرور",
  "Book Room": "غرفة الكتاب",
  "Booking Submission": "تقديم الحجز",
  "Enter amount you wish to pay from wallet":
  "أدخل المبلغ الذي ترغب في دفعه من المحفظة",
  "Redeem Specific Amount": "استرداد مبلغ محدد",
  "Use maximum wallet balance for the payment":
  "استخدم الحد الأقصى لرصيد المحفظة للدفع",
  "Redeem full wallet balance": "استرداد رصيد المحفظة بالكامل",
  "Book Tour": "جولة الكتاب",
  "Not Set": "غير مضبوط",
  "Not set": "غير مضبوط",
  "Book Transport": "النقل الكتاب",
  "Number": "رقم",
  "Extra Prices": "أسعار إضافية",
  "DETAIL": "التفاصيل",
  "Agent Comission": "وكيل الوكيل",
  "Agent comission": "وكيل الوكيل",
  "Apply Instruction": "تطبيق التعليمات",
  "No data to display": "لا توجد بيانات لعرض",
  "You are not logged in, \n please login to access all features":
  "لم تقم بتسجيل الدخول ، يرجى تسجيل الدخول للوصول إلى جميع الميزات",
  "Create account": "إصنع حساب",
  "Log In": "تسجيل الدخول",
  "Login": "تسجيل الدخول",
  "Don\'t have account? Sign up": "ليس لديك حساب؟ اشترك",
  "Have account? Log in": "هل لديك حساب؟ تسجيل الدخول",
  "Confirm Password": "تأكيد كلمة المرور",
  "Sign up": "سجل",
  "I have read and accept the Terms and Privacy Policy":
  "لقد قرأت البنود وسياسة الخصوصية وأوافق عليها",
  "Overview": "نظرة عامة",
  "Home": "الصفحة الرئيسية",
  "Favourite": "مفضل",
  "Profile": "الملف الشخصي",
  "Search": "بحث",
  "History": "التاريخ",
  "Report": "نقل",
  "Currency": "عملة",
  "Settings": "الإعدادات",
  "Language": "لغة",
  "Visa": "تأشيرة دخول",
  "Log out": "تسجيل خروج",
  "Password": "كلمه السر",
  "Could not log out": "تعذر تسجيل الخروج",
  "ALL BOOKING": "كل الحجز",
  "COMPLETED": "منجز",
  "PROCESSING": "معالجة",
  "CONFIRMED": "تم تأكيد",
  "CANCELLED": "ألغيت",
  "PAID": "دفع",
  "UNPAID": "غير مدفوع",
  "Booking History": "سجل الحجز",
  "View info": "عرض المعلومات",
  "Type": "اكتب",
  "Cost": "كلفة",
  "Order date": "تاريخ الطلب",
  "Start date": "تاريخ البدء",
  "End date": "تاريخ الانتهاء",
  "Status": "الحالة",
  "Booking Status": "وضع الحجز",
  "Booking Date": "تاريخ الحجز",
  "Payment Method": "طريقة الدفع او السداد",
  "Duration": "المدة الزمنية",
  "Guests": "ضيوف",
  "Service fee": "رسوم الخدمة",
  "Discount": "خصم",
  "Booking detail": "تفاصيل الحجز",
  "Booking Detail": "تفاصيل الحجز",
  "User detail": "تفاصيل المستخدم",
  "First name": "الاسم الاول",
  "Last name": "الكنية",
  "Balance": "الرصيد الحالي",
  "Reward points": "نقاط المكافأة الحالية",
  "Create request": "إنشاء طلب",
  "Convert points to balance": "تحويل النقاط إلى رصيد",
  "My Wallet": "محفظتي",
  "Wallet history": "سجل المحفظة",
  "Reward History": "تاريخ المكافأة",
  "Amount": "كمية",
  "Date": "تاريخ",
  "Purpose": "هدف",
  "Debit": "مدين",
  "Credit": "ائتمان",
  "Request Date": "تاريخ الطلب",
  "Processing Date": "تاريخ المعالجة",
  "Info": "معلومات",
  "Change Currency": "تغيير العملة",
  "Business name": "الاسم التجاري",
  "Email": "البريد الإلكتروني",
  "Phone": "هاتف",
  "Birthday": "عيد الميلاد",
  "About yourself": "عن نفسك",
  "Address": "عنوان",
  "Alternative address": "عنوان بديل",
  "City": "مدينة",
  "State": "حالة",
  "Country": "بلد",
  "Zip code": "الرمز البريدي",
  "Save": "حفظ",
  "must be filled": "يجب أن يملأ",
  "Select nationality": "حدد الجنسية",
  "Select destination": "حدد وجهتك",
  "Search and apply for visa online":
  "البحث والتقدم للحصول على تأشيرة عبر الإنترنت",
  "Change Password": "تغيير كلمة السر",
  "Enter Current password": "إدخل كلمة السر الحالية",
  "Enter New password": "أدخل كلمة مرور جديدة",
  "Confirm New password": "تأكيد كلمة المرور الجديدة",
  "Cancel": "إلغاء",
  "Change": "يتغيرون",
  "No data to display": "لا توجد بيانات لعرض",
  "Search Tour": "جولة البحث",
  "Search Hotels, Tour, Room, Transport all over the world":
  "ابحث عن الفنادق ، والجولات ، والغرف ، والنقل في جميع أنحاء العالم",
  "Tours": "جولات",
  "Hotels": "الفنادق",
  "Rooms": "غرف",
  "Transport": "المواصلات",
  "Transports": "النقل",
  "Search Destination": "وجهة البحث",
  "Choose date": "اختر موعدا",
  "Starting date": "تاريخ البدء",
  "Ending date": "تاريخ الانتهاء",
  "Room": "غرف",
  "Child": "طفل",
  "Adult": "بالغ",
  "Adults": "بالغ",
  "Search tour": "جولة البحث",
  "Search Hotels": "البحث عن الفنادق",
  "Search Hotel": "ابحث عن فندق",
  "Search Room": "غرفة البحث",
  "Search Rooms": "غرفة البحث",
  "Search Transport": "نقل البحث",
  "Search Transports": "البحث عن وسائل النقل",
  "Where would you\nlike to go?": "أين تريد أن تذهب؟",
  "Offers": "عروض",
  "Apply for visa": "تأشيرة دخول",
  "Travel tips": "نصائح سفر",
  "Bestseller Listing": "قائمة الأكثر مبيعا",
  "Top Destination": "الوجهة الأعلى",
  "Top Destinations": "أهم الوجهات",
  "Our best promotion tours": "أفضل جولاتنا الترويجية",
  "See All": "اظهار الكل",
  "Okay": "حسنا",
  "Close": "قريب",
  "No record": "لا سجلات",
  "Apply now": "قدم الآن",
  "Visa Cost": "تكلفة التأشيرة",
  "Processing Cost": "تكلفة المعالجة",
  "Processing time": "وقت المعالجة",
  "Basic Information": "معلومات اساسية",
  "Apply for visa": "تأشيرة دخول",
  "Add Applicant": "طلب للحصول على تأشيرة",
  "No applicant added": "لم يتم إضافة مقدم طلب",
  "Processing Time and Fee": "পوقت المعالجة والرسوم",
  "Add": "أضف",
  "Total visa cost": "إجمالي تكلفة التأشيرة",
  "General Information": "معلومات عامة",
  "Revision and Payment": "المراجعة والدفع",
  "Done and Payment": "تم والدفع",
  "Book Transports Easily": "كتاب النقل بسهولة",
  "Find  Tours Easily": "البحث عن الجولات بسهولة",
  "Find rooms easily": "اعثر على الغرف بسهولة",
  "Find hotels easily": "البحث عن الفنادق بسهولة",
  "Search Tours": "جولات البحث",
  "results": "النتائج",
  "Book now": "احجز الآن",
  "Book Now": "احجز الآن",
  "Total price": "السعر الكلي",
  "you must choose starting and ending date":
  "يجب عليك اختيار تاريخ البدء والانتهاء",
  "you must choose starting date": "يجب عليك اختيار تاريخ البدء",
  "Please choose ending date": "يرجى اختيار تاريخ الانتهاء",
  "Please choose number of people": "يرجى اختيار عدد من الناس",
  "Check availability": "গالتحقق من الصلاحية",
  "Choose your date, find room , \n book and enjoy":
  "اختر موعدك ، ابحث عن غرفة ،\n احجز واستمتع",
  "Book Hotel": "حجز فندق",
  "Choose date, person number and book hotel":
  "اختر التاريخ ورقم الشخص وحجز الفندق",
  "Submit": "إرسال",
  "Total Adults": "مجموع البالغين",
  "Total Children": "مجموع الأطفال",
  "Total guest": "إجمالي الضيف",
  "Booked Rooms": "حجز غرف",
  "Total": "مجموع",
  "Pay using": "ادفع باستخدام",
  "Your total wallet balance": "إجمالي رصيد محفظتك",
};

Map<String, String> French = {
  "Forgot password ?" : "Mot de passe oublié ?",
  "Recover password" : "Récupérer mot de passe",
  "Title": "Titre",
  "Leave a review": "Laisser un commentaire",
  "Review content": "Examiner le contenu",
  "Service": "Un service",
  "Organization": "Organisation",
  "Friendliness": "La convivialité",
  "Area Expert": "Expert régional",
  "Safety": "sécurité",
  "No reviews to display": "Aucun avis à afficher",
  "Menu": "Menu",
  "Edit Profile": "Editer le profil",
  "Notification": "Notification",
  "Excluded": "Exclus",
  "Included": "Inclus",
  "Reviews": "Commentaires",
  "You might also like": "Vous pourriez aussi aimer",
  "Please Enter Email": "Veuillez saisir votre e-mail",
  "Please Enter Password": "Veuillez entrer le mot de passe",
  "Book Room": "Salle de lecture",
  "Booking Submission": "Soumission de réservation",
  "Enter amount you wish to pay from wallet":
  "Entrez le montant que vous souhaitez payer à partir du portefeuille",
  "Redeem Specific Amount": "Utiliser un montant spécifique",
  "Use maximum wallet balance for the payment":
  "Utiliser le solde maximal du portefeuille pour le paiement",
  "Redeem full wallet balance": "Utiliser le solde complet du portefeuille",
  "Book Tour": "Tour du livre",
  "Not Set": "Pas encore défini",
  "Not set": "Pas encore défini",
  "Book Transport": "Transport de livres",
  "Number": "Nombre",
  "Extra Prices": "Prix supplémentaires",
  "DETAIL": "DÉTAIL",
  "Agent Comission": "Commission d'agent",
  "Agent comission": "Commission d'agent",
  "Apply Instruction": "Appliquer l'instruction",
  "No data to display": "Aucune donnée à afficher",
  "You are not logged in, \n please login to access all features":
  "Vous n'êtes pas connecté, veuillez vous connecter pour accéder à toutes les fonctionnalités",
  "Create account": "Créer un compte",
  "Log In": "S'identifier",
  "Login": "S'identifier",
  "Don\'t have account? Sign up": "Vous n'avez pas de compte? Inscrivez-vous",
  "Have account? Log in": "Vous avez un compte? Connectez-vous",
  "Confirm Password": "Confirmez le mot de passe",
  "Sign up": "S'inscrire",
  "I have read and accept the Terms and Privacy Policy":
  "J'ai lu et j'accepte les conditions générales et la politique de confidentialité",
  "Overview": "Aperçu",
  "Home": "Accueil",
  "Favourite": "les préféré",
  "Profile": "Profil",
  "Search": "Chercher",
  "History": "Histoire",
  "Report": "Rapport",
  "Currency": "Devise",
  "Settings": "Réglages",
  "Language": "Langue",
  "Visa": "Visa",
  "Log out": "Se déconnecter",
  "Password": "Mot de passe",
  "Could not log out": "Impossible de se déconnecter",
  "ALL BOOKING": "TOUTE RESERVATION",
  "COMPLETED": "TERMINÉ",
  "PROCESSING": "EN TRAITEMENT",
  "CONFIRMED": "CONFIRMÉ",
  "CANCELLED": "ANNULÉ",
  "PAID": "PAYÉ",
  "UNPAID": "NON PAYÉ",
  "Booking History": "Historique des réservations",
  "View info": "Afficher les informations",
  "Type": "le type",
  "Cost": "Coût",
  "Order date": "Date de commande",
  "Start date": "Date de début",
  "End date": "Date de fin",
  "Status": "Statut",
  "Booking Status": "Statut de réservation",
  "Booking Date": "Date de réservation",
  "Payment Method": "Mode de paiement",
  "Duration": "Durée",
  "Guests": "Invités",
  "Service fee": "Frais de service",
  "Discount": "Remise",
  "Booking detail": "Détail de la réservation",
  "Booking Detail": "Détail de la réservation",
  "User detail": "Détails de l'utilisateur",
  "First name": "Prénom",
  "Last name": "Nom de famille",
  "Balance": "Solde actuel",
  "Reward points": "Points de récompense actuels",
  "Create request": "Créer une demande",
  "Convert points to balance": "Convertir des points en équilibre",
  "My Wallet": "Mon portefeuille",
  "Wallet history": "Historique du portefeuille",
  "Reward History": "Historique des récompenses",
  "Amount": "Montant",
  "Date": "Date",
  "Purpose": "Objectif",
  "Debit": "Débit",
  "Credit": "Crédit",
  "Request Date": "Date de la demande",
  "Processing Date": "Date de traitement",
  "Info": "Info",
  "Change Currency": "Changer de devise",
  "Business name": "Nom commercial",
  "Email": "Email",
  "Phone": "Téléphone",
  "Birthday": "Anniversaire",
  "About yourself": "A propos de toi",
  "Address": "Adresse",
  "Alternative address": "Adresse alternative",
  "City": "Ville",
  "State": "Etat",
  "Country": "Pays",
  "Zip code": "Code postal",
  "Save": "Sauvegarder",
  "must be filled": "doit être rempli",
  "Select nationality": "Sélectionnez la nationalité",
  "Select destination": "Sélectionner la destination",
  "Search and apply for visa online": "Rechercher et demander un visa en ligne",
  "Change Password": "Changer le mot de passe",
  "Enter Current password": "Entrer le mot de passe actuel",
  "Enter New password": "Entrez un nouveau mot de passe",
  "Confirm New password": "Confirmer le nouveau mot de passe",
  "Cancel": "Annuler",
  "Change": "Changement",
  "No data to display": "Aucune donnée à afficher",
  "Search Tour": "Tour de recherche",
  "Search Hotels, Tour, Room, Transport all over the world":
  "Recherche d'hôtels, circuits, chambres, transports dans le monde entier",
  "Tours": "Tours",
  "Hotels": "Hôtels",
  "Rooms": "Pièces",
  "Transport": "Transport",
  "Transports": "Transport",
  "Search Destination": "Destination de recherche",
  "Choose date": "Choisissez la date",
  "Starting date": "Date de début",
  "Ending date": "Date de Fin",
  "Room": "Pièce",
  "Child": "Enfant",
  "Adult": "Adulte",
  "Adults": "Adulte",
  "Search tour": "Tour de recherche",
  "Search Hotels": "Recherche d'hôtels",
  "Search Hotel": "Rechercher un hôtel",
  "Search Room": "Salle de recherche",
  "Search Rooms": "Salle de recherche",
  "Search Transport": "Rechercher Transport",
  "Search Transports": "Rechercher Transport",
  "Where would you\nlike to go?": "Où voudrais-tu aller?",
  "Offers": "Des offres",
  "Apply for visa": "Demander un visa",
  "Travel tips": "Conseil de voyage",
  "Bestseller Listing": "Liste des meilleures ventes",
  "Top Destination": "Destination de choix",
  "Top Destinations": "Destination de choix",
  "Our best promotion tours": "Nos meilleurs tours de promotion",
  "See All": "Voir tout",
  "Okay": "d'accord",
  "Close": "d'accord",
  "No record": "Aucun enregistrement",
  "Apply now": "Appliquer maintenant",
  "Visa Cost": "Coût du visa",
  "Processing Cost": "Coût de traitement",
  "Processing time": "Temps de traitement",
  "Basic Information": "Informations de base",
  "Apply for visa": "Demander un visa",
  "Add Applicant": "Ajouter un demandeur",
  "No applicant added": "Aucun demandeur ajouté",
  "Processing Time and Fee": "Délai et frais de traitement",
  "Add": "Ajouter",
  "Total visa cost": "Coût total du visa",
  "General Information": "Informations générales",
  "Revision and Payment": "Révision et paiement",
  "Done and Payment": "Terminé et paiement",
  "Book Transports Easily": "Réservez facilement vos transports",
  "Find  Tours Easily": "Trouvez facilement des circuits",
  "Find rooms easily": "Trouvez facilement des chambres",
  "Find hotels easily": "Trouvez facilement des hôtels",
  "Search Tours": "Rechercher des circuits",
  "results": "résultats",
  "Book now": "Reserve maintenant",
  "Book Now": "Reserve maintenant",
  "Total price": "Prix ​​total",
  "you must choose starting and ending date":
  "vous devez choisir la date de début et de fin",
  "you must choose starting date": "vous devez choisir la date de début",
  "Please choose ending date": "Veuillez choisir la date de fin",
  "Please choose number of people": "Veuillez choisir le nombre de personnes",
  "Check availability": "Voir les disponibilités",
  "Choose your date, find room , \n book and enjoy":
  "Choisissez votre date, trouvez une chambre, réservez et profitez",
  "Book Hotel": "Réserver un hôtel",
  "Choose date, person number and book hotel":
  "Choisissez la date, le numéro de personne et réservez l'hôtel",
  "Submit": "Soumettre",
  "Total Adults": "Total adultes",
  "Total Children": "Total d'enfants",
  "Total guest": "Total invité",
  "Booked Rooms": "Chambres réservées",
  "Total": "Total",
  "Pay using": "Payer avec",
  "Your total wallet balance": "Votre solde total de portefeuille",
};
